### ISSUE TITLE
Publishing this Plugin on Moodle.org

### ISSUE THREAD

**Issue by ralferlebach** [logicexpertise/moodle-mod_onlyoffice#5]
Hi,

I am really so excited to find your project on the OnlyOffice forum and on github. Actually I was looking for an online collaboration writing tool like that for a long time - and I would like to participate as much as I can.

Therefore I would like to strongly encurage you to publish this on moodle.org - as soon as this plugin appears there in the plugin section, I will going to translate that in German and maybe other languages like Japanese or Chinese as well.

Also, it might be a good idea to open a discussion stream in the General Moodle Developer forum
https://moodle.org/mod/forum/view.php?id=55

There you might find a helping hand for this project. (I will also ask the IT department of my university if they will commit to that project, if this is published officially on the moodle website.)

So, please keep on your good work!

Greetings

Ralf

**Comment by logicexpertise** [comment]
Thanks Ralf, for your kind words, and suggestions.

The plugin needs a bit of work in order to be ready for publishing in the Moodle plugins database, and I'll do that over the next couple of weeks.

Cheers,
Muyi

**Comment by Dagefoerde** [comment]
Hi @logicexpertise, thanks for developing a plugin that integrates OnlyOffice with Moodle! That is awesome! At our institution we are using both, Moodle and OnlyOffice, but not (yet) in combination.

I have recently advised a colleague during the implementation of the [mod_collabora](https://github.com/learnweb/moodle-mod_collabora) plugin that we have published to the Moodle plugins directory and that is currently seeing increased adoption by the Moodle community. Basically, I think that the teaching scenarios of mod_collabora and your plugin (and, thus, your target audiences) are quite similar and only differ in the software that is available to them. The features of mod_collabora are quite useful and we would love to see them in the OnlyOffice activity module as well!

A partnering institution and I are planning to port the mod_collabora features to an OnlyOffice plugin. To us, there are three options:

a) implement an entirely new mod_onlyoffice plugin,
b) create a fork of your plugin and maintain that, or
c) contribute our changes to your plugin in order to achieve a single, full-featured OnlyOffice integration with Moodle.

We would definitely prefer to do the latter: Contribute to your plugin and improve it in a joint effort. I think that the community would benefit the most from that. In this process, we would not expect any development effort from your part except reviewing and merging the pull requests that follow.

Please let me know what you think! If you would prefer to discuss this in private, please do reach out via email (http://erc.is/p/j.d for contact details). Either way, do keep up the good work. Thanks!

All the best,
Jan

**Comment by logicexpertise** [comment]
Hi @Dagefoerde ,
I think your proposal to contribute to my plugin will take the pluging further along the path to being published on Moodle.org.
Please feel free to open you PRs and I'll review & merge if approved.
I look forward to collaborating with you and your partnering institution and to providing Moodle users an enhanced collaborative document editing experience.
Cheers,
Muyi
